// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDybHlAz5myljQP5VN2XbAly5qLu2JRiLA',
    appId: '1:543115661864:web:c4041f3d9665f49c711b1d',
    messagingSenderId: '543115661864',
    projectId: 'koumishop-3fdfa',
    authDomain: 'koumishop-3fdfa.firebaseapp.com',
    storageBucket: 'koumishop-3fdfa.appspot.com',
    measurementId: 'G-7Q3NYVS812',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUDjpWk4IkUxSUzSdns8SHNf73HQHp5-0',
    appId: '1:543115661864:android:66eacadffb6ab8e4711b1d',
    messagingSenderId: '543115661864',
    projectId: 'koumishop-3fdfa',
    storageBucket: 'koumishop-3fdfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC87TtcPRwqJLIoe_88u9H-yA0Ed7_JK1g',
    appId: '1:543115661864:ios:b7b4fc2de54b6952711b1d',
    messagingSenderId: '543115661864',
    projectId: 'koumishop-3fdfa',
    storageBucket: 'koumishop-3fdfa.appspot.com',
    androidClientId: '543115661864-16ka6v8c06domth2cl7ed1gah5pe1cag.apps.googleusercontent.com',
    iosClientId: '543115661864-504sl18e3dvnr3ql308nuimnrhvef07e.apps.googleusercontent.com',
    iosBundleId: 'com.koumi.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC87TtcPRwqJLIoe_88u9H-yA0Ed7_JK1g',
    appId: '1:543115661864:ios:471c81f080eecf94711b1d',
    messagingSenderId: '543115661864',
    projectId: 'koumishop-3fdfa',
    storageBucket: 'koumishop-3fdfa.appspot.com',
    androidClientId: '543115661864-16ka6v8c06domth2cl7ed1gah5pe1cag.apps.googleusercontent.com',
    iosClientId: '543115661864-4hhs93nmiakhsg5jqoib5n1thghl9bu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.koumishop',
  );
}
